<HEAD>
  <SCRIPT>
function tale_window(strURL) {
 window.open(strURL,'scrollframe','width=900,height=600,scrollbars,menubar=no,status=no');
}
function tale_music(strURL) {
	window.open(strURL,'scrollframe','width=100,height=50,scrollbars,menubar=no,status=no');
}
</SCRIPT>
  <STYLE>
A:link { text-decoration: none; color:#000000 }
A:visited { text-decoration: none; color:#000000 }
A:active { text-decoration: none; color:#000000 }
A:hover { text-decoration: none; color:#000000 }
</STYLE>
  <TITLE>The Baronship of Cove</TITLE>
  <LINK REL=STYLESHEET HREF="norm.css" TYPE="text/css">
</HEAD>
<BODY bgcolor="#0C5003" background="bocimages/grassbg.gif" topmargin="0"
bottommargin="0" LINK="#000000" VLINK="#000000" ALINK="#000000">
<P>
<?php include("eggs.inc"); ?>
<!--- The Roads are no longer safe. Losis Rederic, Endless Rogue --->
<DIV align="center">
  <IMG SRC="bocimages/boctop.jpg" WIDTH=973 HEIGHT=128 BORDER=0 ALT="" USEMAP="#boctop1_Map"><BR>
  <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="973">
    <TR>
      <TD width="224" background="bocimages/contside.gif" valign="top"><TABLE border="0"
	cellspacing="0" cellpadding="0" width="224">
	  <TR>
	    <TD valign="top" background="bocimages/leftable.gif"><DIV align="center">
		<TABLE width="100%" cellspacing="0" cellpadding="10" width="40">
		  <TR>
		    <TD valign="top" width="15"></TD>
		    <TD valign="top"><?php include("menu.inc"); ?></TD>
		  </TR>
		</TABLE>
	      </DIV>
	    </TD>
	  </TR>
	  <TR>
	    <TD valign="top"><IMG SRC="bocimages/cont.jpg" WIDTH=224 HEIGHT=222 BORDER=0
		  ALT="" USEMAP="#cont_Map"></TD>
	  </TR>
	</TABLE>
      </TD>
      <TD width="563" background="bocimages/centretable.gif" valign="top"><IMG
	    SRC="bocimages/bocsquads.jpg"><BR>
	<TABLE BORDER CELLPADDING="0" background="bocimages/scrollbgdark.gif" width="100%">
	  <TR>
	    <TD valign="top" class="notes" width="100%">After becoming Juniors, Covian
	      guardsmen may choose to join a Squad. Squads are defined and select groups
	      of guardsmen that are trained in a particular field, rigorously improving
	      their ability and overall combat prowess. A Squad is usually lead by an officer
	      (Sergeant or above), but this is not always necessary. <BR>
	      In the wide confusion of battle, these specialist Squads are renowned for
	      having the required discipline and training to stick to their roles and see
	      the battle fought effectively. They form the core of the Covian Army.<BR>
	      <BR>
	      <TABLE BORDER="0" CELLPADDING="2" WIDTH="550" class="notes">
		<TR>
		  <TD valign="top" width="150" class="notes"><DIV align="center">
		      <BR>
		      <IMG SRC="http://img359.imageshack.us/img359/5143/ahmedsite3ki.png" WIDTH="78"
			  HEIGHT="89">
		    </DIV>
		  </TD>
		  <TD valign="top" width="400" class="notes"><B>1st Baron's Own
		    Grenadiers</B><BR>
		    <I>Commanding: </I>Grenadier Captain Raiden Morana <BR>
		    <I>Tome:</I>
		    <A HREF="http://grenadiers.sugeworld.com" TARGET="_blank">http://grenadiers.sugeworld.com</A>
		    <P>
		    The Baron's Own Grenadiers are the elite both melee and ranged units of the
		    Covian Army. Specialising in both archery and close combat, these guardsmen
		    excel in death from all angles, and provide the raw firepower that leads
		    the Army to victory. They are tough, hardy, and dependable. <BR>
		    These guardsmen are also well known for their role in guarding the Baron
		    of Cove himself, and are sometimes tasked with special errands from Lord
		    Octiovus.
		    <P>
		    <U>Uniform:</U> Full Shadow Platemail, Shadow Heater Shield, Covian Cap,
		    Covian Sash, Covian Kilt, Boots, and Bronze Platemail Arms.
		    <P>
		    <U>Requirements:</U> Must be at least a Junior Guardsman. Must successfully
		    pass Grenadiers Selection.</TD>
		</TR>
	      </TABLE>
	      <P>
	      <TABLE BORDER="0" CELLPADDING="2" WIDTH="550" class="notes">
		<TR>
		  <TD valign="top" width="150" class="notes"><DIV align="center">
		      <BR>
		      <IMG SRC="bocimages/struc-coy.jpg" WIDTH="78" HEIGHT="89">
		    </DIV>
		  </TD>
		  <TD valign="top" width="400" class="notes"><B>2nd Light Company</B><BR>
		    <I>Commanding: </I>Officer Cadet Kal ShadowHand <BR>
		    <P>
		    The Light Company are the eyes and ears of the Covian Army. Silently, they
		    ease through the lands of Britannia, providing the Army and the Baronship
		    with critical intelligence on enemies (and allies). However, nay think these
		    guardsmen are an easy ride. Light Company specialists are extremely well
		    trained with the kryss, a fast and deadly weapon, and also have some knowledge
		    in the art of poisoning.
		    <P>
		    <U>Uniform:</U> Full Green Horned Leather Jacket, Covian Cap, Covian Sash,
		    Covian Kilt, Boots.
		    <P>
		    <U>Requirements:</U> Must be at least a Junior Guardsman. Must pass Scouting
		    Course.
		    <P>
		    <U>Recommended Skills:</U> Stealth, Hiding, Poisoning, and/or Ninjitsu.
		    <P>
		  </TD>
		</TR>
	      </TABLE>
	      <P>
	      <TABLE BORDER="0" CELLPADDING="2" WIDTH="550" class="notes">
		<TR>
		  <TD valign="top" width="150" class="notes"><DIV align="center">
		      <BR>
		      <IMG SRC="http://sugeworld.com/boc/bocimages/struc-high.jpg" WIDTH="78" HEIGHT="89">
		    </DIV>
		  </TD>
		  <TD valign="top" width="400" class="notes"><B>3rd Glenmore Highlanders
		    (DISBANDED)</B><BR>
		    <I>Commanding: </I>...<BR>
		    <P>
		    The Glenmore Highlanders are the Army's heavy infantry, tough and harsh.
		    The Highlanders are the backbone of any advance, though not always being
		    in the fore of the attack. They are the &#147;body&#148; of the Army, as
		    opposed to being the heavy firepower of the Grenadiers, or the full on charge
		    of the Dragoons.<BR>
		    In character the Highlanders have very thick and gruff accents, and they
		    are sticklers for discipline and order. They will not let even minor
		    infringements of the rules go unpunished. They tend to either be completely
		    devoid of a sense of humor, or have a rather bleak and twisted one. They
		    value the fact they had no casualties over a great number of enemies slain.<BR>
		    Due to their heritage in the Glenmore Mountains, they are impervious to bad
		    weather, and enjoy very strong drink, far stronger than the usual Sosarian
		    spirits. <BR>
		    When envisaging these chaps in battle think about the slow moving 'blob'
		    of soldiers. Making sure their brothers stay alive and avoid running off
		    getting themselves or their brothers killed. Other squads can always retreat
		    to their area to heal or they can push an enemy out of a region simply by
		    moving in and refusing to budge.
		    <P>
		    <U>Uniform:</U> Full Shadow Platemail, Shadow Norse Helmet, Bronze Platemail
		    Tunic, Bronze Heater Shield. Covian Cap, Covian Sash, Covian Kilt, Boots.
		    <P>
		    <U>Requirements:</U> Must be at least a Junior Guardsman. Must complete
		    Highlander Trials.
		    <P>
		    <U>Recommended Skills:</U> Parrying! Shields are a MUST!
		    <P>
		  </TD>
		</TR>
	      </TABLE>
	      <P>
	      <TABLE BORDER="0" CELLPADDING="2" WIDTH="550" class="notes">
		<TR>
		  <TD valign="top" width="150" class="notes"><DIV align="center">
		      <BR>
		      <IMG SRC="http://sugeworld.com/boc/bocimages/dragoon.jpg" WIDTH="78" HEIGHT="89">
		    </DIV>
		  </TD>
		  <TD valign="top" width="400" class="notes"><B>4th Altmere Dragoons (DISBANDED) </B><BR>
		    <I>Commanding: </I>...<BR>
		    <P>
		    The Altmere Dragoons are the mobile infantry of the Covian Army. Do NOT be
		    mistaken. These chaps nay ride into battle atop their fine steeds. Their
		    horses are but a method of transport, and thus enable the Dragoons to respond
		    quickly to enemy movement, and relocate their position if and where
		    necessary.<BR>
		    With their horse-riding skill, the Dragoons act also as messengers, their
		    communication between forces providing an essential link, and a winning strategy
		    over foreign armies.<BR>
		    In battle itself, the Dragoons act as skirmishers. Always on the move, these
		    skilled combatants will be at the forefront of any charge, and will engage
		    the Enemy on a hit and run basis.
		    <P>
		    <U>Uniform:</U> Iron Platemail Arms, Gloves, and Gorget. Shadow Chainmail
		    Tunic, Trousers. Covian Cap, Covian Sash, Covian Kilt, Boots.
		    <P>
		    <U>Requirements:</U> Must be at least a Junior Guardsman. Must pass Dragoon
		    Trials.<BR>
		  </TD>
		</TR>
	      </TABLE>
		  <P>
	      <TABLE BORDER="0" CELLPADDING="2" WIDTH="550" class="notes">
		<TR>
		  <TD valign="top" width="150" class="notes"><DIV align="center">
		      <BR>
		     
		    </DIV>
		  </TD>
		  <TD valign="top" width="400" class="notes"><B>The Covian Navy (DISBANDED)</B><BR>
		    <I>Commanding: </I>...<BR>
		    <P>
		    The original Covian Navy was founded over a decade ago by his Lordship, Baron Octiovus, 
			and had initial success in mapping the islands around Cove and engaging and destroying 
			many Orcish vessels.<br>
			However, during the Orcish occupation of Cove, the Navy was surrounded. And despite the valiant efforts of 
			the Naval defenders, the entire fleet was sunk.<br>
			It is said the ghosts of those sailors 
			killed by the Orcs now haunt the Covian docks.<p>

Since then, there has been no official Covian Navy, but rather a loose collection of ships working to keep 
Orcish and pirate vessels out of Cove’s water ways, and launching occasional mapping missions with limited 
success. However, the Baron has decided the time is nigh for Cove to rule the waves once more.
		    <P>
		    <U>Uniform:</U> Dyed Shadow Leather. Dyed Blue Sleeves, Gloves, and Gorget. Blue Skullcap, Covian Sash, Covian Kilt, Boots.
		    <P>
		    <U>Requirements:</U> Must be at least a Junior Guardsman. Must adhere to Sailor Requirements.<BR>
		  </TD>
		</TR>
	      </TABLE>
	    </TD>
	  </TR>
	</TABLE>
      </TD>
      <TD width="186" background="bocimages/righttable.gif" valign="top"><!---Wooden
	Table--->
	<TABLE width="100%" cellspacing="0" cellpadding="0" width="186">
	  <TR>
	    <TD valign="top" width="17"></TD>
	    <TD valign="top" class="notes"><?php include("board.inc");
	      ?></TD>
	  </TR>
	</TABLE>
      </TD>
    </TR>
    <TR>
      <TD valign="top"><IMG SRC="bocimages/leftbot.gif" WIDTH="224" HEIGHT="12"></TD>
      <TD valign="top"><IMG SRC="bocimages/centrebot.gif" WIDTH="563" HEIGHT="12"></TD>
      <TD valign="top"><IMG SRC="bocimages/rightbot.gif" WIDTH=186 HEIGHT=12 BORDER=0
	    ALT="" USEMAP="#rightbot_Map"></TD>
    </TR>
  </TABLE>
</DIV>
<P>
<BR>
<DIV align="right">
  <?php include("footer.inc"); ?>
</DIV>
</BODY>