<MAP NAME="cont_Map">
  <AREA SHAPE="rect" ALT="Find Out Latest News Across Sosaria!" COORDS="27,54,188,105"
      HREF="JavaScript:tale_window('http://cove.sugeworld.com/forum/index.php?topic=15932.0')">
</MAP>
<MAP NAME="boctop1_Map">
  <AREA SHAPE="poly" ALT="The Music of Cove..." COORDS="940,117, 943,124, 953,124, 958,118, 960,113, 962,107, 956,103"
      HREF="javascript:tale_music('tales/music.html')">
</MAP>
<MAP NAME="rightbot_Map">
  <AREA SHAPE="rect" ALT="The darker side of Cove awaits..." COORDS="160,0,176,6"
      HREF="javascript:tale_window('tales/dark.html')"
      border="0">
</MAP>
