<table width="100%" cellspacing="0" cellpadding="0" class="titre"><tr><td valign="top"><B><U>Main</U><BR>
		    <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php">Latest News</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=aboutus">About Us</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=contacts">Contacts</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=apply">Apply!</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="forum/">Forum</A><BR>
		      <BR>
		      <U>Covian Army</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=armystructure">Structure</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=armysquads">Squads</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A HREF="index.php?page=orders">Tactical Orders</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A HREF="index.php?page=armypromotion">Promotion</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=honours">Honours</A><BR>
		      <br>
		      <U>Citizenry</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=council">The Council</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=citizenry">Citizens</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=districts">Town Districts</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=criminals">Crime</A><BR>
		      <br>
		      <U>Culture</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=roleplaying">Roleplaying </A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=religion">Religion</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=events">Events</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=locations">Key Locations</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=legends">Legends &amp; Tales</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=laws">Law</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=profiles">Profiles</A><BR>
		      <BR>
		      <U>Community</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="JavaScript:tale_window('http://cove.sugeworld.com/forum/index.php?topic=14670.0')">OOC Rules</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="JavaScript:tale_window('http://cove.sugeworld.com/forum/index.php?topic=10109.0')">Diplomacy</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="bocimages/pointer.gif">
		      <A href="index.php?page=links">Tome References</A><BR></B></td></tr></table>
