<table width="100%" cellspacing="0" cellpadding="0" class="titre"><tr><td valign="top"><B><U>Main</U><BR>
		    <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://cove.fantasyworld.nl/news/covenews.php">Latest News</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/about.php">About Us</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/contacts.php">Contacts</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/join.php">Apply!</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://cove.fantasyworld.nl/forum/index.php">Forum</A><BR>
		      <BR>
		      <U>Covian Army</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/militia.php">Structure</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/honours.php">Honours</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/units.php">Squads</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A HREF="http://sugeworld.com/boc/orders.php">Tactical
		      Orders</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A HREF="http://sugeworld.com/boc/promotion.php">Promotion</A><BR>
		      <BR>
		      <U>Culture</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/roleplay.php">Roleplaying </A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/religion.php">Religion</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/events.php">Events</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/locations.php">Key Locations</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/legends.php">Legends &amp; Tales</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/laws.php">Law</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      Old News <A href="http://cove.fantasyworld.nl/news/oldnews.php">#1</A>, <A HREF="http://cove.fantasyworld.nl/news/oldnews.php?news=33">#2</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/profiles.php">Profiles</A><BR>
		      <BR>
		      <U>Community</U><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/roe.php">OOC Rules</A><BR>
		      <IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="JavaScript:tale_window('http://cove.fantasyworld.nl/forum/index.php/topic,10109.0.html')">Diplomacy</A><BR>
<IMG WIDTH="19" HEIGHT="13" SRC="http://sugeworld.com/boc/bocimages/pointer.gif">
		      <A href="http://sugeworld.com/boc/links.php">Tome References</A><BR></B></td></tr></table>